{"name": "Проверка ответа на запрос с неверным паролем", "status": "passed", "start": 1747679218068, "stop": 1747679218439, "uuid": "7d85a91f-2526-4732-966b-35d3eb3f9438", "historyId": "7b59ea21293aa51d8fb438826b986f6c", "testCaseId": "7b59ea21293aa51d8fb438826b986f6c", "fullName": "tests.test_authentication.TestAuthentication#test_auth_with_wrong_passwd_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authentication"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "cat"}, {"name": "thread", "value": "12084-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authentication"}]}